# Generated by Django 4.2.19 on 2025-04-27 07:17

from django.db import migrations
import json
import os


class Migration(migrations.Migration):

    dependencies = [
        ('signature', '0002_auto_20250427_0714'),
    ]

    
    operations = [
        
    ]
