# Generated by Django 4.2.17 on 2025-02-25 01:45

from django.db import migrations
from signature.models import Major


class Migration(migrations.Migration):
    def InsertMajors():
        Major.objects.create(name='Computer Science', faculty='Engineering')

    dependencies = [
        ('signature', '0002_major_faculty'),
    ]

    operations = [
        migrations.RunPython(InsertMajors),
    ]
