# Generated by Django 4.2.19 on 2025-04-27 07:25

from django.db import migrations
import json


class Migration(migrations.Migration):

    dependencies = [
        ('signature', '0003_auto_20250427_0717'),
    ]

    def insert_students(apps, schema_editor):
        Student = apps.get_model('signature', 'Student')
        with open('signature/migrations/students.json', 'r') as file:
            students = json.load(file)
            for student in students:

                found_major = apps.get_model('signature', 'Major').objects.filter(
                    name=student['Carrera']
                )
                current_student = Student.objects.create(
                    rut=student['Rut'],
                    dv=student['DV'],
                    first_name=student['Nombre1'],
                    second_name=student['Nombre2'],
                    last_name=student['Apellido1'],
                    second_last_name=student['Apellido2'],
                    major=found_major.first()
                )

    operations = [
        migrations.RunPython(
            insert_students
        ),
    ]
