# Generated by Django 4.2.19 on 2025-04-27 07:25

from django.db import migrations
import json
import os


class Migration(migrations.Migration):

    dependencies = [
        ('signature', '0003_auto_20250427_0717'),
    ]

    def insert_students(apps, schema_editor):
        Student = apps.get_model('signature', 'Student')
        base_dir = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
        json_path = os.path.join(base_dir, 'data', 'students.json')
        with open(json_path, 'r', encoding='utf-8') as file:
            students = json.load(file)
            for student in students:
                found_major = apps.get_model('signature', 'Major').objects.filter(
                    name=student['Carrera']
                )
                Student.objects.create(
                    rut=student['Rut'],
                    dv=student['DV'],
                    first_name=student['Nombre1'],
                    second_name=student['Nombre2'],
                    last_name=student['Apellido1'],
                    second_last_name=student['Apellido2'],
                    major=found_major.first()
                )

    operations = [
        migrations.RunPython(
            insert_students
        ),
    ]
