# Generated by Django 4.2.17 on 2025-02-25 02:40

from django.db import migrations
import json
from signature.models import Subject, Major


class Migration(migrations.Migration):
    def InsertSubjects(models, schema_editor):
        f = open('subjects.json')
        data = json.load(f)

        for subject in data:
            major = subject.get('major')
            found_major = Major.objects.get(name=major)

            if found_major:
                added_subject = Subject.objects.create(name=subject.get(
                    'name'))
                added_subject.major.add(found_major)
            else:
                print(f"Major {major} not found")

        # Closing file
        f.close()

    dependencies = [
        ('signature', '0004_subject'),
    ]
    operations = [
        migrations.RunPython(InsertSubjects),
    ]
