# Generated by Django 5.2 on 2025-05-18 17:20

import signature.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signature', '0005_relate_students_subjects'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='permissionuser',
            managers=[
                ('objects', signature.models.CustomUserManager()),
            ],
        ),
    ]
