# Generated by Django 4.2.17 on 2025-02-25 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signature', '0005_insert_subjects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='major',
            field=models.ManyToManyField(related_name='subjects', to='signature.major'),
        ),
    ]
