# Generated by Django 4.2.17 on 2025-02-25 03:47

from django.db import migrations
from signature.models import Subject


class Migration(migrations.Migration):
    def DeleteSubjects(models, schema_editor):
        Subject.objects.all().delete()

    dependencies = [
        ('signature', '0006_alter_subject_major'),
    ]

    operations = [
        migrations.RunPython(DeleteSubjects),
    ]
