# Generated by Django 5.2.1 on 2025-05-25 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signature', '0006_alter_permissionuser_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='MajorCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=15)),
            ],
        ),
        migrations.AlterField(
            model_name='major',
            name='faculty',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='major',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AddField(
            model_name='major',
            name='code',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='majors', to='signature.majorcode'),
        ),
    ]
