# Generated by Django 5.2.1 on 2025-05-25 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signature', '0007_majorcode_alter_major_faculty_alter_major_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='major',
            name='code',
        ),
        migrations.AddField(
            model_name='majorcode',
            name='major',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='codes', to='signature.major'),
        ),
    ]
