# Generated by Django 5.2.1 on 2025-05-25 04:51

from django.db import migrations


class Migration(migrations.Migration):

    def add_major_codes(apps, schema_editor):
        MajorCode = apps.get_model('signature', 'MajorCode')
        Major = apps.get_model('signature', 'Major')

        major_codes = ['CC', 'IC', 'IM', 'IA', 'IS', 'IN']
        for code in major_codes:
            MajorCode.objects.create(code=code)

        # Assign MajorCode to existing Majors
        for major in Major.objects.all():
            if major.code is None:
                major.code = MajorCode.objects.first()

    dependencies = [
        ('signature', '0007_majorcode_alter_major_faculty_alter_major_name_and_more'),
    ]

    operations = [
    ]
