# Generated by Django 4.2.17 on 2025-02-25 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signature', '0008_reinsert_subjects'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=20)),
                ('dv', models.CharField(max_length=1)),
                ('first_name', models.CharField(max_length=200)),
                ('second_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('second_last_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='major',
            name='students',
            field=models.ManyToManyField(related_name='majors', to='signature.student'),
        ),
        migrations.AddField(
            model_name='subject',
            name='students',
            field=models.ManyToManyField(related_name='subjects', to='signature.student'),
        ),
    ]
