# Generated by Django 5.2.1 on 2025-05-25 05:19

from django.db import migrations
import pandas as pd


class Migration(migrations.Migration):

    def add_major_codes(apps, schema_editor):
        MajorCode = apps.get_model('signature', 'MajorCode')
        Major = apps.get_model('signature', 'Major')

        df = pd.read_csv('major_codes.csv')
        df['UWMMAHI_PROGRAMA'] = df['UWMMAHI_PROGRAMA'].str.upper()

        for major in df['UWMMAHI_PROGRAMA']:
            found_major = Major.objects.filter(name=major).first()
            if found_major:
                print(f"Found major: {found_major.name}")
                major_codes = df[df['UWMMAHI_PROGRAMA']
                                 == found_major.name]['UWMMAHI_PROGRAM']
                for code in major_codes:
                    # Check if the code already exists
                    existing_code = MajorCode.objects.filter(
                        code=code, major=found_major).first()
                    if not existing_code:
                        MajorCode.objects.create(
                            code=code, major=found_major)

    dependencies = [
        ('signature', '0008_remove_major_code_majorcode_major'),
    ]

    operations = [
        migrations.RunPython(add_major_codes),
    ]
