# Generated by Django 5.2.1 on 2025-06-08 01:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signature', '0009_relate_code_majors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='major',
        ),
        migrations.AddField(
            model_name='subject',
            name='major',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='signature.major'),
        ),
    ]
