# Generated by Django 4.2.17 on 2025-02-25 06:10

from django.db import migrations
from signature.models import Major, Subject, Student
import json


class Migration(migrations.Migration):
    def InsertStudents(models, schema_editor):
        f = open('students.json')
        data = json.load(f)

        for student in data:
            print(student)
            major = student.get('Carrera')
            subject = student.get('Asignatura')
            rut = student.get('Rut')
            dv = student.get('DV')
            first_name = student.get('Nombre1')
            second_name = student.get('Nombre2')
            last_name = student.get('Apellido1')
            second_last_name = student.get('Apellido2')
            found_major = Major.objects.get(name=major)
            found_subject, created = Subject.objects.get_or_create(
                name=subject) if subject else (0, 0)
            if found_subject != 0:
                found_subject.major.add(found_major)

            added_student = Student.objects.create(
                first_name=first_name, second_name=second_name, last_name=last_name, second_last_name=second_last_name, rut=rut, dv=dv)
            if found_major:
                added_student.majors.add(found_major)
            else:
                print(f"Major {found_major} not found")
            if found_subject != 0:
                added_student.subjects.add(found_subject)
            else:
                print(f"Subject {found_subject} not found")

    dependencies = [
        ('signature', '0009_student_major_students_subject_students'),
    ]

    operations = [
        migrations.RunPython(InsertStudents),
    ]
