# Generated by Django 5.2.2 on 2025-06-08 02:35

from django.db import migrations
import json
import os

class Migration(migrations.Migration):

    dependencies = [
        ('signature', '0010_remove_subject_major_subject_major'),
    ]

    def insert_subjects(apps, schema_editor):
        Subject = apps.get_model('signature', 'Subject')
        Major = apps.get_model('signature', 'Major')
        
        base_dir = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
        json_path = os.path.join(base_dir, 'data', 'majors.json')
        
        with open(json_path, 'r', encoding='utf-8') as file:
            majors_data = json.load(file)
            
            for major_data in majors_data:
                # Obtener la carrera (major) correspondiente
                try:
                    major_instance = Major.objects.get(name=major_data['major'])
                except Major.DoesNotExist:
                    print(f"Carrera '{major_data['major']}' no encontrada. Saltando asignaturas.")
                    continue
                
                # Crear cada asignatura y asociarla con la carrera
                for subject_name in major_data['subjects']:
                    # Verificar si la asignatura ya existe
                    subject, created = Subject.objects.get_or_create(
                        name=subject_name
                    )
                    if subject:
                        subject.major = major_instance
                        subject.save()
                    else:
                        created.major = major_instance
                        created.save()


                    
    operations = [
        migrations.RunPython(
            insert_subjects
        ),
    ]
