# Generated by Django 4.2.17 on 2025-02-25 03:47

from django.db import migrations
from signature.models import Student


class Migration(migrations.Migration):
    def DeleteStudents(models, schema_editor):
        Student.objects.all().delete()

    dependencies = [
        ('signature', '0010_insert_students'),
    ]

    operations = [
        migrations.RunPython(DeleteStudents),
    ]
