# Generated by Django 4.2.17 on 2025-02-26 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signature', '0011_delete_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='major',
            name='students',
        ),
        migrations.AddField(
            model_name='student',
            name='major',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='signature.major'),
            preserve_default=False,
        ),
    ]
