# Generated by Django 5.1.6 on 2025-03-02 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signature', '0013_reinsert_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='subject',
            field=models.ManyToManyField(related_name='subjects', to='signature.subject'),
        ),
    ]
