# Generated by Django 5.1.6 on 2025-03-05 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signature', '0014_student_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='subject',
        ),
    ]
