name: CI Pipeline

on:
  push:
    branches: [main]

jobs:
  test:
    timeout-minutes: 1
    name: Run Tests
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest]
        python-version: [3.9, 3.11]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4 

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        python manage.py runserver & sleep 5 && pytest
