name: CI Pipeline

on:
  push:
  #   branches:
  #     - develop
  # pull_request:
  #   branches:
  #     - develop

jobs:
  test:
    timeout-minutes: 2
    name: Run Tests
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.9, 3.11]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          python manage.py runserver & echo $! > server.pid
          sleep 5

          pytest
          TEST_EXIT_CODE=$?

          kill $(cat server.pid)

          exit $TEST_EXIT_CODE
