name: CI Pipeline

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main

jobs:
  deploy:
    environment: signature
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Tailscale
      uses: tailscale/github-action@v3
      with:
        oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
        oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
        tags: tag:fisica

    - name: SSH Gidua
      uses: appleboy/ssh-action@v1.2.2
      with:
        host: gidua
        username: server
        key: ${{ secrets.SSH_KEY }}
        password: ${{ secrets.PASSWORD_GIDUA }}
        port: 22
        script: |
          cd /var/www/example.org/Signature-Rest-Api 
          git reset --hard
          sleep 5 && git pull
          export LD_LIBRARY_PATH=$(nix-instantiate --eval -E '(import <nixpkgs> {}).stdenv.cc.cc.lib.outPath' | tr -d '"')/lib
          uv run manage.py makemigrations
          uv run manage.py migrate
          echo '${{ secrets.PASSWORD_GIDUA }}' | sudo -S systemctl restart signature
    - name: Logout of Tailscale
      run: tailscale logout

  test:
    timeout-minutes: 2
    name: Run Tests
    runs-on: ${{ matrix.os }}
    environment: signature

    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.9, 3.11]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt


      - name: Run tests
        run: |
          pytest . -k "not test_email_token" 

      - name: Cyclomatic Complexity
        run: |
          radon cc signature/ -s

      - name: Maintainability Index
        run: |
          radon mi signature/ -s

      - name: General Metrics
        run: |
          radon raw signature/ -s

      - name: Halstead Metrics
        run: |
          radon hal signature/
